#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WP_ÖDEV
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="STOK")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMARKA(MARKA instance);
    partial void UpdateMARKA(MARKA instance);
    partial void DeleteMARKA(MARKA instance);
    partial void InsertMÜŞTERİ(MÜŞTERİ instance);
    partial void UpdateMÜŞTERİ(MÜŞTERİ instance);
    partial void DeleteMÜŞTERİ(MÜŞTERİ instance);
    partial void InsertÜRÜN(ÜRÜN instance);
    partial void UpdateÜRÜN(ÜRÜN instance);
    partial void DeleteÜRÜN(ÜRÜN instance);
    partial void InsertPERSONEL(PERSONEL instance);
    partial void UpdatePERSONEL(PERSONEL instance);
    partial void DeletePERSONEL(PERSONEL instance);
    partial void InsertSATIŞ(SATIŞ instance);
    partial void UpdateSATIŞ(SATIŞ instance);
    partial void DeleteSATIŞ(SATIŞ instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WP_ÖDEV.Properties.Settings.Default.STOKConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MARKA> MARKAs
		{
			get
			{
				return this.GetTable<MARKA>();
			}
		}
		
		public System.Data.Linq.Table<MÜŞTERİ> MÜŞTERİs
		{
			get
			{
				return this.GetTable<MÜŞTERİ>();
			}
		}
		
		public System.Data.Linq.Table<ÜRÜN> ÜRÜNs
		{
			get
			{
				return this.GetTable<ÜRÜN>();
			}
		}
		
		public System.Data.Linq.Table<PERSONEL> PERSONELs
		{
			get
			{
				return this.GetTable<PERSONEL>();
			}
		}
		
		public System.Data.Linq.Table<SATIŞ> SATIŞs
		{
			get
			{
				return this.GetTable<SATIŞ>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MARKA")]
	public partial class MARKA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MarkaNO;
		
		private string _MarkaAdı;
		
		private EntitySet<ÜRÜN> _ÜRÜNs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMarkaNOChanging(int value);
    partial void OnMarkaNOChanged();
    partial void OnMarkaAdıChanging(string value);
    partial void OnMarkaAdıChanged();
    #endregion
		
		public MARKA()
		{
			this._ÜRÜNs = new EntitySet<ÜRÜN>(new Action<ÜRÜN>(this.attach_ÜRÜNs), new Action<ÜRÜN>(this.detach_ÜRÜNs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkaNO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MarkaNO
		{
			get
			{
				return this._MarkaNO;
			}
			set
			{
				if ((this._MarkaNO != value))
				{
					this.OnMarkaNOChanging(value);
					this.SendPropertyChanging();
					this._MarkaNO = value;
					this.SendPropertyChanged("MarkaNO");
					this.OnMarkaNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkaAdı", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string MarkaAdı
		{
			get
			{
				return this._MarkaAdı;
			}
			set
			{
				if ((this._MarkaAdı != value))
				{
					this.OnMarkaAdıChanging(value);
					this.SendPropertyChanging();
					this._MarkaAdı = value;
					this.SendPropertyChanged("MarkaAdı");
					this.OnMarkaAdıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MARKA_ÜRÜN", Storage="_ÜRÜNs", ThisKey="MarkaNO", OtherKey="MarkaNO")]
		public EntitySet<ÜRÜN> ÜRÜNs
		{
			get
			{
				return this._ÜRÜNs;
			}
			set
			{
				this._ÜRÜNs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ÜRÜNs(ÜRÜN entity)
		{
			this.SendPropertyChanging();
			entity.MARKA = this;
		}
		
		private void detach_ÜRÜNs(ÜRÜN entity)
		{
			this.SendPropertyChanging();
			entity.MARKA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MÜŞTERİ")]
	public partial class MÜŞTERİ : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MüşteriTC;
		
		private string _MüşteriAdı;
		
		private string _Telefon;
		
		private string _Adres;
		
		private EntitySet<SATIŞ> _SATIŞs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMüşteriTCChanging(string value);
    partial void OnMüşteriTCChanged();
    partial void OnMüşteriAdıChanging(string value);
    partial void OnMüşteriAdıChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    #endregion
		
		public MÜŞTERİ()
		{
			this._SATIŞs = new EntitySet<SATIŞ>(new Action<SATIŞ>(this.attach_SATIŞs), new Action<SATIŞ>(this.detach_SATIŞs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MüşteriTC", DbType="VarChar(11) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MüşteriTC
		{
			get
			{
				return this._MüşteriTC;
			}
			set
			{
				if ((this._MüşteriTC != value))
				{
					this.OnMüşteriTCChanging(value);
					this.SendPropertyChanging();
					this._MüşteriTC = value;
					this.SendPropertyChanged("MüşteriTC");
					this.OnMüşteriTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MüşteriAdı", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string MüşteriAdı
		{
			get
			{
				return this._MüşteriAdı;
			}
			set
			{
				if ((this._MüşteriAdı != value))
				{
					this.OnMüşteriAdıChanging(value);
					this.SendPropertyChanging();
					this._MüşteriAdı = value;
					this.SendPropertyChanged("MüşteriAdı");
					this.OnMüşteriAdıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="VarChar(50)")]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MÜŞTERİ_SATIŞ", Storage="_SATIŞs", ThisKey="MüşteriTC", OtherKey="MüşteriTC")]
		public EntitySet<SATIŞ> SATIŞs
		{
			get
			{
				return this._SATIŞs;
			}
			set
			{
				this._SATIŞs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SATIŞs(SATIŞ entity)
		{
			this.SendPropertyChanging();
			entity.MÜŞTERİ = this;
		}
		
		private void detach_SATIŞs(SATIŞ entity)
		{
			this.SendPropertyChanging();
			entity.MÜŞTERİ = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ÜRÜN")]
	public partial class ÜRÜN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ÜrünNO;
		
		private System.Nullable<int> _MarkaNO;
		
		private string _ÜrünAdı;
		
		private double _AlışFiyat;
		
		private System.Nullable<double> _SatışFiyat;
		
		private int _Stok;
		
		private EntitySet<SATIŞ> _SATIŞs;
		
		private EntityRef<MARKA> _MARKA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnÜrünNOChanging(int value);
    partial void OnÜrünNOChanged();
    partial void OnMarkaNOChanging(System.Nullable<int> value);
    partial void OnMarkaNOChanged();
    partial void OnÜrünAdıChanging(string value);
    partial void OnÜrünAdıChanged();
    partial void OnAlışFiyatChanging(double value);
    partial void OnAlışFiyatChanged();
    partial void OnSatışFiyatChanging(System.Nullable<double> value);
    partial void OnSatışFiyatChanged();
    partial void OnStokChanging(int value);
    partial void OnStokChanged();
    #endregion
		
		public ÜRÜN()
		{
			this._SATIŞs = new EntitySet<SATIŞ>(new Action<SATIŞ>(this.attach_SATIŞs), new Action<SATIŞ>(this.detach_SATIŞs));
			this._MARKA = default(EntityRef<MARKA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ÜrünNO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ÜrünNO
		{
			get
			{
				return this._ÜrünNO;
			}
			set
			{
				if ((this._ÜrünNO != value))
				{
					this.OnÜrünNOChanging(value);
					this.SendPropertyChanging();
					this._ÜrünNO = value;
					this.SendPropertyChanged("ÜrünNO");
					this.OnÜrünNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkaNO", DbType="Int")]
		public System.Nullable<int> MarkaNO
		{
			get
			{
				return this._MarkaNO;
			}
			set
			{
				if ((this._MarkaNO != value))
				{
					if (this._MARKA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMarkaNOChanging(value);
					this.SendPropertyChanging();
					this._MarkaNO = value;
					this.SendPropertyChanged("MarkaNO");
					this.OnMarkaNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ÜrünAdı", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string ÜrünAdı
		{
			get
			{
				return this._ÜrünAdı;
			}
			set
			{
				if ((this._ÜrünAdı != value))
				{
					this.OnÜrünAdıChanging(value);
					this.SendPropertyChanging();
					this._ÜrünAdı = value;
					this.SendPropertyChanged("ÜrünAdı");
					this.OnÜrünAdıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlışFiyat", DbType="Float NOT NULL")]
		public double AlışFiyat
		{
			get
			{
				return this._AlışFiyat;
			}
			set
			{
				if ((this._AlışFiyat != value))
				{
					this.OnAlışFiyatChanging(value);
					this.SendPropertyChanging();
					this._AlışFiyat = value;
					this.SendPropertyChanged("AlışFiyat");
					this.OnAlışFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SatışFiyat", DbType="Float")]
		public System.Nullable<double> SatışFiyat
		{
			get
			{
				return this._SatışFiyat;
			}
			set
			{
				if ((this._SatışFiyat != value))
				{
					this.OnSatışFiyatChanging(value);
					this.SendPropertyChanging();
					this._SatışFiyat = value;
					this.SendPropertyChanged("SatışFiyat");
					this.OnSatışFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stok", DbType="Int NOT NULL")]
		public int Stok
		{
			get
			{
				return this._Stok;
			}
			set
			{
				if ((this._Stok != value))
				{
					this.OnStokChanging(value);
					this.SendPropertyChanging();
					this._Stok = value;
					this.SendPropertyChanged("Stok");
					this.OnStokChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ÜRÜN_SATIŞ", Storage="_SATIŞs", ThisKey="ÜrünNO", OtherKey="ÜrünNO")]
		public EntitySet<SATIŞ> SATIŞs
		{
			get
			{
				return this._SATIŞs;
			}
			set
			{
				this._SATIŞs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MARKA_ÜRÜN", Storage="_MARKA", ThisKey="MarkaNO", OtherKey="MarkaNO", IsForeignKey=true)]
		public MARKA MARKA
		{
			get
			{
				return this._MARKA.Entity;
			}
			set
			{
				MARKA previousValue = this._MARKA.Entity;
				if (((previousValue != value) 
							|| (this._MARKA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MARKA.Entity = null;
						previousValue.ÜRÜNs.Remove(this);
					}
					this._MARKA.Entity = value;
					if ((value != null))
					{
						value.ÜRÜNs.Add(this);
						this._MarkaNO = value.MarkaNO;
					}
					else
					{
						this._MarkaNO = default(Nullable<int>);
					}
					this.SendPropertyChanged("MARKA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SATIŞs(SATIŞ entity)
		{
			this.SendPropertyChanging();
			entity.ÜRÜN = this;
		}
		
		private void detach_SATIŞs(SATIŞ entity)
		{
			this.SendPropertyChanging();
			entity.ÜRÜN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PERSONEL")]
	public partial class PERSONEL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PersonelTC;
		
		private string _PersonelAdı;
		
		private string _Telefon;
		
		private string _Adres;
		
		private string _Şifre;
		
		private string _Durum;
		
		private System.Nullable<int> _YaptığıSatışSayısı;
		
		private System.Nullable<double> _SatışlardanEldeEttiğiMiktar;
		
		private EntitySet<SATIŞ> _SATIŞs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPersonelTCChanging(string value);
    partial void OnPersonelTCChanged();
    partial void OnPersonelAdıChanging(string value);
    partial void OnPersonelAdıChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnŞifreChanging(string value);
    partial void OnŞifreChanged();
    partial void OnDurumChanging(string value);
    partial void OnDurumChanged();
    partial void OnYaptığıSatışSayısıChanging(System.Nullable<int> value);
    partial void OnYaptığıSatışSayısıChanged();
    partial void OnSatışlardanEldeEttiğiMiktarChanging(System.Nullable<double> value);
    partial void OnSatışlardanEldeEttiğiMiktarChanged();
    #endregion
		
		public PERSONEL()
		{
			this._SATIŞs = new EntitySet<SATIŞ>(new Action<SATIŞ>(this.attach_SATIŞs), new Action<SATIŞ>(this.detach_SATIŞs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelTC", DbType="VarChar(11) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PersonelTC
		{
			get
			{
				return this._PersonelTC;
			}
			set
			{
				if ((this._PersonelTC != value))
				{
					this.OnPersonelTCChanging(value);
					this.SendPropertyChanging();
					this._PersonelTC = value;
					this.SendPropertyChanged("PersonelTC");
					this.OnPersonelTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelAdı", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string PersonelAdı
		{
			get
			{
				return this._PersonelAdı;
			}
			set
			{
				if ((this._PersonelAdı != value))
				{
					this.OnPersonelAdıChanging(value);
					this.SendPropertyChanging();
					this._PersonelAdı = value;
					this.SendPropertyChanged("PersonelAdı");
					this.OnPersonelAdıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="VarChar(50)")]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Şifre", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string Şifre
		{
			get
			{
				return this._Şifre;
			}
			set
			{
				if ((this._Şifre != value))
				{
					this.OnŞifreChanging(value);
					this.SendPropertyChanging();
					this._Şifre = value;
					this.SendPropertyChanged("Şifre");
					this.OnŞifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Durum", DbType="VarChar(16)")]
		public string Durum
		{
			get
			{
				return this._Durum;
			}
			set
			{
				if ((this._Durum != value))
				{
					this.OnDurumChanging(value);
					this.SendPropertyChanging();
					this._Durum = value;
					this.SendPropertyChanged("Durum");
					this.OnDurumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YaptığıSatışSayısı", DbType="Int")]
		public System.Nullable<int> YaptığıSatışSayısı
		{
			get
			{
				return this._YaptığıSatışSayısı;
			}
			set
			{
				if ((this._YaptığıSatışSayısı != value))
				{
					this.OnYaptığıSatışSayısıChanging(value);
					this.SendPropertyChanging();
					this._YaptığıSatışSayısı = value;
					this.SendPropertyChanged("YaptığıSatışSayısı");
					this.OnYaptığıSatışSayısıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SatışlardanEldeEttiğiMiktar", DbType="Float")]
		public System.Nullable<double> SatışlardanEldeEttiğiMiktar
		{
			get
			{
				return this._SatışlardanEldeEttiğiMiktar;
			}
			set
			{
				if ((this._SatışlardanEldeEttiğiMiktar != value))
				{
					this.OnSatışlardanEldeEttiğiMiktarChanging(value);
					this.SendPropertyChanging();
					this._SatışlardanEldeEttiğiMiktar = value;
					this.SendPropertyChanged("SatışlardanEldeEttiğiMiktar");
					this.OnSatışlardanEldeEttiğiMiktarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PERSONEL_SATIŞ", Storage="_SATIŞs", ThisKey="PersonelTC", OtherKey="PersonelTC")]
		public EntitySet<SATIŞ> SATIŞs
		{
			get
			{
				return this._SATIŞs;
			}
			set
			{
				this._SATIŞs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SATIŞs(SATIŞ entity)
		{
			this.SendPropertyChanging();
			entity.PERSONEL = this;
		}
		
		private void detach_SATIŞs(SATIŞ entity)
		{
			this.SendPropertyChanging();
			entity.PERSONEL = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SATIŞ")]
	public partial class SATIŞ : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FaturaNO;
		
		private string _PersonelTC;
		
		private string _MüşteriTC;
		
		private System.Nullable<int> _ÜrünNO;
		
		private System.DateTime _Tarih;
		
		private System.Nullable<double> _Fiyat;
		
		private int _Adet;
		
		private string _Durum;
		
		private EntityRef<MÜŞTERİ> _MÜŞTERİ;
		
		private EntityRef<PERSONEL> _PERSONEL;
		
		private EntityRef<ÜRÜN> _ÜRÜN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFaturaNOChanging(int value);
    partial void OnFaturaNOChanged();
    partial void OnPersonelTCChanging(string value);
    partial void OnPersonelTCChanged();
    partial void OnMüşteriTCChanging(string value);
    partial void OnMüşteriTCChanged();
    partial void OnÜrünNOChanging(System.Nullable<int> value);
    partial void OnÜrünNOChanged();
    partial void OnTarihChanging(System.DateTime value);
    partial void OnTarihChanged();
    partial void OnFiyatChanging(System.Nullable<double> value);
    partial void OnFiyatChanged();
    partial void OnAdetChanging(int value);
    partial void OnAdetChanged();
    partial void OnDurumChanging(string value);
    partial void OnDurumChanged();
    #endregion
		
		public SATIŞ()
		{
			this._MÜŞTERİ = default(EntityRef<MÜŞTERİ>);
			this._PERSONEL = default(EntityRef<PERSONEL>);
			this._ÜRÜN = default(EntityRef<ÜRÜN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaturaNO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int FaturaNO
		{
			get
			{
				return this._FaturaNO;
			}
			set
			{
				if ((this._FaturaNO != value))
				{
					this.OnFaturaNOChanging(value);
					this.SendPropertyChanging();
					this._FaturaNO = value;
					this.SendPropertyChanged("FaturaNO");
					this.OnFaturaNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelTC", DbType="VarChar(11)")]
		public string PersonelTC
		{
			get
			{
				return this._PersonelTC;
			}
			set
			{
				if ((this._PersonelTC != value))
				{
					if (this._PERSONEL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPersonelTCChanging(value);
					this.SendPropertyChanging();
					this._PersonelTC = value;
					this.SendPropertyChanged("PersonelTC");
					this.OnPersonelTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MüşteriTC", DbType="VarChar(11)")]
		public string MüşteriTC
		{
			get
			{
				return this._MüşteriTC;
			}
			set
			{
				if ((this._MüşteriTC != value))
				{
					if (this._MÜŞTERİ.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMüşteriTCChanging(value);
					this.SendPropertyChanging();
					this._MüşteriTC = value;
					this.SendPropertyChanged("MüşteriTC");
					this.OnMüşteriTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ÜrünNO", DbType="Int")]
		public System.Nullable<int> ÜrünNO
		{
			get
			{
				return this._ÜrünNO;
			}
			set
			{
				if ((this._ÜrünNO != value))
				{
					if (this._ÜRÜN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnÜrünNOChanging(value);
					this.SendPropertyChanging();
					this._ÜrünNO = value;
					this.SendPropertyChanged("ÜrünNO");
					this.OnÜrünNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="Date NOT NULL")]
		public System.DateTime Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fiyat", DbType="Float")]
		public System.Nullable<double> Fiyat
		{
			get
			{
				return this._Fiyat;
			}
			set
			{
				if ((this._Fiyat != value))
				{
					this.OnFiyatChanging(value);
					this.SendPropertyChanging();
					this._Fiyat = value;
					this.SendPropertyChanged("Fiyat");
					this.OnFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adet", DbType="Int NOT NULL")]
		public int Adet
		{
			get
			{
				return this._Adet;
			}
			set
			{
				if ((this._Adet != value))
				{
					this.OnAdetChanging(value);
					this.SendPropertyChanging();
					this._Adet = value;
					this.SendPropertyChanged("Adet");
					this.OnAdetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Durum", DbType="VarChar(1)")]
		public string Durum
		{
			get
			{
				return this._Durum;
			}
			set
			{
				if ((this._Durum != value))
				{
					this.OnDurumChanging(value);
					this.SendPropertyChanging();
					this._Durum = value;
					this.SendPropertyChanged("Durum");
					this.OnDurumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MÜŞTERİ_SATIŞ", Storage="_MÜŞTERİ", ThisKey="MüşteriTC", OtherKey="MüşteriTC", IsForeignKey=true)]
		public MÜŞTERİ MÜŞTERİ
		{
			get
			{
				return this._MÜŞTERİ.Entity;
			}
			set
			{
				MÜŞTERİ previousValue = this._MÜŞTERİ.Entity;
				if (((previousValue != value) 
							|| (this._MÜŞTERİ.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MÜŞTERİ.Entity = null;
						previousValue.SATIŞs.Remove(this);
					}
					this._MÜŞTERİ.Entity = value;
					if ((value != null))
					{
						value.SATIŞs.Add(this);
						this._MüşteriTC = value.MüşteriTC;
					}
					else
					{
						this._MüşteriTC = default(string);
					}
					this.SendPropertyChanged("MÜŞTERİ");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PERSONEL_SATIŞ", Storage="_PERSONEL", ThisKey="PersonelTC", OtherKey="PersonelTC", IsForeignKey=true)]
		public PERSONEL PERSONEL
		{
			get
			{
				return this._PERSONEL.Entity;
			}
			set
			{
				PERSONEL previousValue = this._PERSONEL.Entity;
				if (((previousValue != value) 
							|| (this._PERSONEL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PERSONEL.Entity = null;
						previousValue.SATIŞs.Remove(this);
					}
					this._PERSONEL.Entity = value;
					if ((value != null))
					{
						value.SATIŞs.Add(this);
						this._PersonelTC = value.PersonelTC;
					}
					else
					{
						this._PersonelTC = default(string);
					}
					this.SendPropertyChanged("PERSONEL");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ÜRÜN_SATIŞ", Storage="_ÜRÜN", ThisKey="ÜrünNO", OtherKey="ÜrünNO", IsForeignKey=true)]
		public ÜRÜN ÜRÜN
		{
			get
			{
				return this._ÜRÜN.Entity;
			}
			set
			{
				ÜRÜN previousValue = this._ÜRÜN.Entity;
				if (((previousValue != value) 
							|| (this._ÜRÜN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ÜRÜN.Entity = null;
						previousValue.SATIŞs.Remove(this);
					}
					this._ÜRÜN.Entity = value;
					if ((value != null))
					{
						value.SATIŞs.Add(this);
						this._ÜrünNO = value.ÜrünNO;
					}
					else
					{
						this._ÜrünNO = default(Nullable<int>);
					}
					this.SendPropertyChanged("ÜRÜN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
